// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALPb14RVlp8fMLQgwcVWfs-e_qtvrL7Iw',
    appId: '1:894993737231:web:980f8b7e09b8c9b004a57a',
    messagingSenderId: '894993737231',
    projectId: 'chat-app-38a50',
    authDomain: 'chat-app-38a50.firebaseapp.com',
    storageBucket: 'chat-app-38a50.appspot.com',
    measurementId: 'G-YSP3QWXCGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3H5iMo7uPEm0ql3w2w1LlE3tCquW0-E4',
    appId: '1:894993737231:android:3064837e7909751304a57a',
    messagingSenderId: '894993737231',
    projectId: 'chat-app-38a50',
    storageBucket: 'chat-app-38a50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-p59dY8I6G2QMS4zun-pKFmysK38o70E',
    appId: '1:894993737231:ios:e3e71a6155b7f6d904a57a',
    messagingSenderId: '894993737231',
    projectId: 'chat-app-38a50',
    storageBucket: 'chat-app-38a50.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-p59dY8I6G2QMS4zun-pKFmysK38o70E',
    appId: '1:894993737231:ios:fc803414387b71ea04a57a',
    messagingSenderId: '894993737231',
    projectId: 'chat-app-38a50',
    storageBucket: 'chat-app-38a50.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
